-- 01_external_odoo.sql — REFERENCE ONLY (no DDL).
--
-- Menu, modifiers, categories, combos, tables and restaurant data are owned by the
-- Odoo POS database (see menu_restaurant_schema.md). The voice-ordering app READS
-- these tables; it never creates or alters them. Our own tables (carts, sessions,
-- transcripts, server calls, order confirmations) reference Odoo rows by their
-- INTEGER primary key as a *soft* reference — no cross-schema foreign keys, because
-- Odoo's ORM owns those tables' lifecycle.
--
-- Odoo stores translatable text as jsonb: name = {"en_US":"…","zh_CN":"…"}. This
-- covers multi-language (FR5) directly — no separate translation tables needed.
-- Odoo language codes are res.lang style ("en_US","zh_CN","fr_FR","es_ES").
--
-- Concept → Odoo table (id column we reference):
--
--   restaurant / POS ......... pos_config                         (pos_config_id)
--   menu item (catalog) ...... product_template                   (product_tmpl_id)
--   menu item (sellable) ..... product_product                    (product_id)
--   item availability ........ product_template.available_in_pos / .active
--   item price ............... product_template.list_price (numeric)
--   item alt name / SKU ...... product_template.alternative_name / .default_code
--   category (screen) ........ pos_category                       (pos_category_id)
--   category (accounting) .... product_category                   (categ_id)
--   modifier group ........... product_attribute + product_template_attribute_line
--   modifier value (generic).. product_attribute_value            (product_attribute_value_id)
--   modifier value (per item). product_template_attribute_value   (ptav_id)  ← carries price_extra
--   modifier price ........... product_template_attribute_value.price_extra
--                              / product_attribute_value.default_extra_price
--   combo group .............. product_combo                      (combo_id)
--   combo choice ............. product_combo_item                 (product_id, extra_price)
--   floor / area ............. restaurant_floor                   (floor_id)
--   table .................... restaurant_table                   (restaurant_table_id)
--   confirmed order .......... pos_order / pos_order_line          (pos_order_id)
--   course firing ............ restaurant_order_course
--
-- Scoping tables to a POS: restaurant_table.floor_id → restaurant_floor, then
-- restaurant_floor ↔ pos_config via pos_config_restaurant_floor_rel.
--
-- The LLM/cart contract in design §8 uses `menu_item_key` / `modifier_key`. At this
-- data layer those map to Odoo integer ids: menu_item_key → product_tmpl_id (or the
-- product_product variant), modifier_key → product_template_attribute_value.id. The
-- Menu Candidate Matcher performs the mapping between Odoo rows and the payload.
